spring:
  application:
    name: hardis-portal
  profiles:
    active: ${apollo_profile}
  resources:
    cache-period: 3600

server:
  port: 8080
  
logging:
  file: /opt/logs/100003173/hardis-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP

security:
  user:
    name: hardis
    password: admin


